openapi: 3.0.1
info:
  title: Swagger Petstore
  description: 'This is a sample server Petstore server.'
  contact:
    name: Jane Smith
    url: https://path/to/somewhere
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: https://petstore.swagger.io/v2
tags:
  - name: user
    description: Operations about user
paths:
  /user:
    $ref: 'user/user.api.yaml#/User'
